---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 27100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: bonvoyage/flask-hello-world:1.0.0
        #understanding flask application requests and limits using LOCUST - https://learnk8s.io/setting-cpu-memory-limits-requests
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        # Readiness prob would have been checking another endpoint if I had one to see if the service is ready to serve traffic
        # e.g if we had a database such as mongo it would have pinged the db to see if its ready and then conclude that the container is ready to receive traffic
        # readinessProbe:
        #   exec:
        #     command:
        #     - mongo
        #     - --eval
        #     - db.adminCommand('ping')
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 5
          timeoutSeconds: 5    
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-hello-world-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 25
        periodSeconds: 60
---
#creating a service account so flask is recognizeable in the k8s env and can communicate with the kubernetel control plane via its api ( for future uses such as interacting with other pods )
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-service-account
  namespace: default

