apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
  namespace: default
spec:
  ports:
  - nodePort: 27100
    port: 5000
    targetPort: 5000
  selector:
    app: flask-hello-world
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - image: bonvoyage/flask-hello-world:1.0.1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: flask-hello-world
        ports:
        - containerPort: 5000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 16Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
  namespace: default
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 4
      - periodSeconds: 60
        type: Percent
        value: 20
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-hello-world-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-service-account
  namespace: default
